### PR TITLE
1.1 spec - Removed: currentAPI, gppData, tcData. Added: signalStatus,…

### PR DESCRIPTION
**Pull request by chuff**
… applicableSections. Replaced api return values with callbacks

### CODE REVIEW

**Review by nealrosen — APPROVED** [review]
Code looks great to me.  I will also integrate this into our CMP dev environment to test out the functionality.

**Comment by nealrosen** [comment]
Thanks for this update Chad.  While testing this PR in our CMP, I noticed something unexpected.  Let me know if you'd prefer that I create a separate issue for this.

The addEventListener command responds with success=true in the initial listenerRegistered event.  Subsequent calls to the callback have success=undefined.  The spec isn't as clear as it could be on this point.  It states that success will be false if the CMP fails to process the command.  That technically means that any value other than false denotes a successful processing of the command.  Though to avoid potential confusion, I would suggest setting success to true in those subsequent calls to the callback.  This would align with how the tcfapi responds to its addEventListener command.

**Comment by chuff** [comment]
Good catch. No need for a separate ticket, I'll update the PR this evening.

**Comment by chuff** [comment]
Done.

**Comment by nealrosen** [comment]
Thanks.  One more thing, related to supportedAPIs.  I'm not sure how the supportedAPIs value will be interpreted or used by vendor scripts.  If a CMP does not intend to initialize values for each of those APIs / sections, shouldn't the CMP be able to override the default supportedAPIs value to include only those that it fully supports?

**Comment by nealrosen** [comment]
I'm rethinking the need for making the supportedAPIs configurable.  
- I see you updated the CmpApi to support this.  But the stub still returns a hardcoded list.  Without wrapping the stub logic in a function that takes supportedAPIs as a parameter, I don't see how the stub could support this.
- More importantly, I just noticed the documentation for the parsedSections property.  It states that the parsedSections property represents the sections present in the gpp string whereas the supportedAPIs represents all possible APIs / sections that the CMP could support.  It seems unnecessary for a CMP to advertise that it supports 11:usutv1 (for example) when it would never have that section in the string, but I'm not sure it would impact functionality if vendor scripts rely on the parsedSections.  I guess I don't see how supportedAPIs is intended to be used.

> parsedSections: Object // The parsedSections property represents an object of all parsed sections of the gppString property that are supported by the API on this page (see supportedAPIs property). The object contains one property for each supported API with the name of the API as the property name and the value as a parsed representation of this section (similar to getSection command). If a section is supported but not represented in the gppString, it is omitted in the parsedSections object.

**Review by nealrosen — APPROVED** [review]

**Review by nealrosen — CHANGES_REQUESTED** [review]
I tried to build this branch locally and encountered errors due to mismatched capitalization in a few filenames.  (GVL, GVLError, GVLMapItem, GVLSetMap, IDSetMap)

I suspect you changed the capitalization of those files locally, but Git doesn't do a great job of handling renaming files with just capitalization changes.  So, when you pushed the commit, the filenames did not change.  

To resolve this, you may need to delete or rename them (ex. Gvl.js -> Gvl_dummy.js).  Save that change in a commit, then rename Gvl_dummy.js -> GVL.js and save that change in a separate commit.

**Comment by chuff** [comment]
Thank you for catching that Neal. I think that should be fixed now.

**Review by nealrosen — APPROVED** [review]
Looks great to me.  I've built and copied this branch into our CMP to test it out and it seems to be working very well.

**Pull request merged**
